* Tasks
** DONE Comment Toyota-Lada
   CLOSED: [2018-06-19 Вт 00:00]
** DONE Comment Porsche-Audi
   CLOSED: [2018-06-19 Вт 00:00]
** DONE Algo
   CLOSED: [2018-06-19 Вт 00:14]
** DONE Usage
   CLOSED: [2018-06-19 Вт 00:00]

* Report

** Введение

 Разработанное приложение позволяет находить пути между
 заданными объектами вплоть до некоторой длины.
 С помощью свойств и значений можно выявить интересные
 взаимосвязи, а более глубокий обход позволяет сопоставить
 значения, которые для объектов одной категории могуть быть заданы
 как напрямую, так и вложенно.

** Примеры

 В качестве первого примера есть Lada Kalina и Toyota 86.
 Из найденных связей на глубине равной 2 выводов кроме тех,
 что это два автомобиля с каким-либо типом кузова не сделать.

 Для Porsche 911 и Audi A5 найдено значительно больше связей:
 форма кузова, эпоха производства, много общего у самих производителей.
 Оба производителя являются немецкими компаниями, входят в Volkswagen Group,
 а обе модели собираются у Audi. Помимо сходств выявляется и особенность:
 в отличие от Audi A5, 911 не является полноприводным, хотя производитель
 опирался на опыт полноприводного Porsche 959.


** Алгоритм работы

Логика работы приложения сводится к разбору полей объектов
и фильтрации оных. Для каждого из искомых объектов выполняется
SPARQL запрос для получения его полей, далее выполняется фильтрация
полей не представляющих интереса. Рекурсивно вплоть до заданной глубины
проводится процедура получения свойств и значений и переход по ним.

После определения совпадений на полученных наборах данных для обоих
объектов строятся пути и удаляются ветви с родительским узлом уже состоящем
в одной из цепочек. Таким образом значительно сокращается объем лишних данных.

Последним шагом является подготовка данных для визуализации, а именно
построение ребер для графа.
